; print	number.
;
; Suitable for use with	the result of itoa.
;
; Entry:
; unk_0	= digit	count
; unk_1... = digits

print_number:				
					
		LDX	#1
		LDY	#0
		LDA	byte_0
                .if tbe_version
                .cerror *!=print_n_chars
                .else
                .if be_version
                jmp print_n_chars
                .else
		JSR	print_n_chars
                .endif
		RTS
                .endif
; End of function print_number
