                ; `validate_mode' is a poor name for this. Pass MODE
                ; 255 in to set things up for the current mode.
validate_mode .proc
                cpy #2
                beq invalid_mode
                cpy #5
                beq invalid_mode
                cpy #8
                bcc L81BD
invalid_mode:
                ldy #7
L81BD:
                sty screen_mode
                ldx screen_mode
get_HIMEM_for_mode_X:                   
                LDY     higher_order_address
                INY
                BNE     is_tube
                LDY     higher_order_address+1
                INY
                BEQ     is_not_tube

                .if tbe_version
is_tube:
                lda #$84   ; OSBYTE read bottom of display RAM address
                bne LB9B0
is_not_tube:
                lda #$85 ; OSBYTE read bottom of display RAM address for given mode
                .else
is_tube:
                lda #0
                sta HIMEM+0
                lda #$80
                sta HIMEM+1                
                RTS

is_not_tube:
                LDA     #133    ;read HIMEM for given MODE
                .endif
                .if tbe_version
LB9B0:
                .endif
                JSR     OSBYTE
                STX     HIMEM
                STY     HIMEM+1
                RTS
; End of function validate_mode
                .endproc
                