#+STARTUP: overview

#+begin_src markdown
  ## New in 1.47

  - * commands are matched case-insensitively, so (e.g.) `*be` now works
  - Reset CTRL+F key behaviour to default when exiting to BASIC
#+end_src

* .dir-locals.el

#+begin_src elisp
  ((nil . ((compile-command . "cd ~/github/basic_editor && make _tom_emacs"))))
#+end_src

#+begin_src elisp
  ((nil . ((compile-command . "cd c:\\tom\\github\\basic_editor && make _tom_emacs"))))
#+end_src

* Variants

** Variant 1

*** Remove *FX19

https://github.com/tom-seddon/basic_editor/blob/fa65f35727f65558b1155e748c550aa3f002c648/releases/1.32_original/basiced.lst#L833

#+begin_src diff
  @@ -32,7 +32,7 @@
  -00000220: a9 07 85 28 a9 13 20 f4 ff a2 69 a0 89 a9 45 20 ...(.. ...i...E
  +00000220: a9 07 85 28 ea ea ea ea ea a2 69 a0 89 a9 45 20 ...(......i...E
                         ^^ ^^ ^^ ^^ ^^
#+end_src

Not sure what the reasoning behind this is?

*** Write bogus stuff to $fe16?

Modifies write_crtc routine: https://github.com/tom-seddon/basic_editor/blob/fa65f35727f65558b1155e748c550aa3f002c648/releases/1.32_original/basiced.lst#L5025

#+begin_src diff
  @@ -441,7 +441,7 @@
  -00001BB0: 98 48 8a a8 a2 00 a9 97 20 f4 ff 68 a8 a2 01 a9 .H...... ..h....
  +00001BB0: 98 48 ea ea a2 16 a9 97 20 f4 ff 68 a8 a2 0a a9 .H...... ..h....
                   ^^ ^^    ^^                         ^^
#+end_src

New code:

#+begin_example
  write_crtc: ; X=CRTC register, Y=value
  pha
  tya
  pha
  nop        ; was txa - A = CRTC register
  nop        ; was tay - Y = CRTC register
  ldx #$16   ; was ldx #$00  ; store to $FE16... ???
  lda #$97
  jsr $fff4
  pla
  tay
  ldx #$0a   ; was ldx #$01
  lda #$97   ; write to $FE0A... ???
#+end_example

I... don't understand.

*** Remove FX19

This routine scrolls the screen down:

https://github.com/tom-seddon/basic_editor/blob/fa65f35727f65558b1155e748c550aa3f002c648/releases/1.32_original/basiced.lst#L10936

#+begin_src diff
  @@ -910,7 +910,7 @@
  -00003900: a2 00 ac bf 06 8c ab 06 20 01 8f a9 13 20 f4 ff ........ .... ..
  +00003900: a2 00 ac bf 06 8c ab 06 20 01 8f ea ea ea ea ea ........ .......
                                              ^^ ^^ ^^ ^^ ^^
#+end_src

Maybe this speeds up the scrolling?

** Variant 2

https://github.com/tom-seddon/basic_editor/blob/fa65f35727f65558b1155e748c550aa3f002c648/releases/1.32_original/basiced.lst#L5849

#+begin_src diff
  -00001F70: 48 a5 10 48 48 a5 3c f0 18 a5 10 cd 00 04 f0 02 H..HH.<.........
  +00001F70: 48 a5 10 48 48 a5 3c f0 18 a5 31 cd 00 04 f0 02 H..HH.<...1.....
                                           ^^
#+end_src

Changes LDA cursor_offset into LDA unk_31 - but unk_31 is apparently
unused?

** Variant 3

https://github.com/tom-seddon/basic_editor/blob/fa65f35727f65558b1155e748c550aa3f002c648/releases/1.32_original/basiced.lst#L3519

#+begin_src diff
  -000013F0: 3e c9 0d f0 08 99 52 00 c8 c0 0f d0 f2 4c 14 83 >.....R......L..
  +000013F0: 3e c9 0d f0 08 99 52 00 c8 c0 0f d0 f2 4c 00 83 >.....R......L..
                                                       ^^
#+end_src

Changes JMP $8314 into JMP $8300 - looks like a bad image as $8300 is
in the middle of an instruction.

** Variant 4

This is the same as my original ROM

** Variant 5

https://github.com/tom-seddon/basic_editor/blob/fa65f35727f65558b1155e748c550aa3f002c648/releases/1.32_original/basiced.lst#L627

#+begin_src diff
  -000000E0: 20 91 8e a2 60 86 31 a2 00 86 3c 86 62 e8 86 3d  ...`.1...<.b..=
  +000000E0: 20 91 8e a2 60 86 31 a2 00 86 62 e8 86 3c 86 3d  ...`.1...b..<.=
                                           ^^ ^^ ^^ ^^
#+end_src

Activate insert mode on startup. Before:

a2 00  ldx #0
86 3c  stx $3c ; 0=overtype, 1=insert
86 62  stx $62
e8     inx

After:

a2 00  ldx #0
86 62  stx $62
e8     inx
86 3c  stx $3c ; 0=overtype, 1/insert

#+begin_src diff
  -00003FF0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
  +00003FF0: 76 20 31 2e 33 32 2b 20 28 49 4e 53 45 52 54 29 v 1.32+ (INSERT)
             ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^
#+end_src

1.32+ indeed! This single change makes a huge improvement. I don't
know what they were thinking, making overtype the default.

* PRES stuff

https://stardot.org.uk/forums/viewtopic.php?f=3&t=7719&start=30#p108512

Vague goals:

1. Figure out what's in the UTILS part

2. Produce an updated ABE mashup like the PRES ABE, but this time
   building from source on PC: updated BE, rebuilt UTILS 

3. Have both types of ABE: 2 x 16 KB banks, or 1 x 32 KB bank switched
   using the PLD board

4. Figure out what the differences between the various versions of the
   UTILS ROM are

** Different UTILS ROMS in this repo

- beeb/1/$.ELECTRON :: built on my BBC B from the source on disk
- beeb/1/$.ELECTRON2 :: built on my BBC B from the source on disk
  after reinstating includes of =ROMID=, =MEMEDIT= and =TXCOPY=
- beeb/1/$.ELK :: came on the disk image - looks like it has a bit
  more in it?

TODO: 32 KB PRES ABE and ABE+ ROMs (from memory actually very similar)

** OSWORD $b5

Input parameter block:

| Offset | What        | Must be | Notes |
|--------+-------------+---------+-------|
| $00    |             |         |       |
| $01    |             |         |       |
| $02    | code        | 0,1,2   |       |
| $03    | check value | B       | X=$00 |
| $04    |             | A       | X=$01 |
| $05    |             | S       | X=$02 |
| $06    |             | I       | X=$03 |
| $07    |             | C       | X=$04 |
| $08    |             |         | X=$05 |
| $09    |             | E       | X=$06 |
| $0a    |             | d       | X=$07 |
| $0b    |             | i       | X=$08 |
| $0c    |             | t       | X=$09 |
| $0d    |             | o       | X=$0a |
| $0e    |             | r       | X=$0b |
| $0f    |             |         | X=$0c |
| $10    |             | &       | X=$0d |
| $11    |             |         | X=$0e |
| $12    |             | T       | X=$0f |
| $13    |             | o       | X=$10 |
| $14    |             | o       | X=$11 |
| $15    |             | l       | X=$12 |
| $16    |             | k       | X=$13 |
| $17    |             | i       | X=$14 |
| $18    |             |         |       |

*** Code=0

See =LBCCA=.

Copy 13 bytes from new_osword_stuff into parameter block starting from
offset 2. Data is: 2,"Load",0,"Append",0

*** Code=1

Enter =BCE6= with A=$4c 76 'L'

*** Code=2

Enter =BCE6= with A=$41 65 'A'

*** What is =BCE6=?

Insert chars in keyboard buffer.

First `L` or `A`.

Then ` `.

Then chars from the OSWORD parameter block, assuming 0-terminated.

(So this runs `LOAD` with A=1 or `APPEND` with A=2.)

** Inter-ROM communication

Both copy a little routine to $A00 that switches to the other ROM then
does a =jmp ($bfee)=.

*** bedit->butils

Entry to each routine:

- A :: reason code, bit 7 clear
- top of stack :: original reason code, all 8 bits

Valid codes are: (bit 7 may additionally be set - purpose unknwon)

**** A=$01 - retrieve error message text

There's a bunch of free space in the BUTILS half so room for some
significantly expanded descriptions.

Entry:

- ?last_error_number :: error to retrieve

Exit:

- error_message_buffer :: filled in with text

**** $02 - handle *HELP

**** $03 - handle * command

**** $04

**** $07

**** $08

**** $0a

*** butils->bedit

**** $02

Call =restore_a8_a9=.

**** $03

Call =restore_a8_a9= or the (somewhat similar, but less well-named...)
=LA960=.

**** $05


**** $0a

Enter command mode assuming language workspace is all set up??

**** $0b

Perform BASIC Editor language initialisation stuff??

* --case-sensitive

expected SHA1: da8feaec70579ecedd9b229872d734ecee065a38

* PRES/Acornsoft differences

Search for =_version= in the pres/bedit folder.

** Ignore

No need to think about these.

*** Ignore: 1 .\pres_bedit.commands.help.s65:47: .if acornsoft_version

Help stuff.

*** Ignore: 2 .\pres_bedit.commands.help.s65:58: .if acornsoft_version

More of #1.

*** Ignore: 3 .\pres_bedit.commands.load.s65:61: .if acornsoft_version

Set BASIC file exec address to $ffff8023.

*** Ignore: 4 .\pres_bedit.commands.load.s65:69: .if acornsoft_version

Set BASIC file exec address to $ffff8023.

*** 5 .\pres_bedit.commands.mode.s65:58: .if *** Ignore: 9 .\pres_bedit.command_table.s65:33: .if acornsoft_version

More of #1.

*** Ignore: 10 .\pres_bedit.command_table.s65:39: .if bet2_version

More of #1.

*** Ignore: 11 .\pres_bedit.command_table.s65:70: .if acornsoft_version

More of #1.

*** Ignore: 12 .\pres_bedit.command_table.s65:76: .if bet2_version

More of #1.

*** Ignore: 14 .\pres_bedit.command_table.s65:122: .if acornsoft_version

Constant for help or something.

*** Ignore: 15 .\pres_bedit.command_table.s65:129: .if acornsoft_version

Constant for help or something.


*** 50 .\pres_bedit.strings.s65:80: .if acornsoft_version

Help text change.

*** 51 .\pres_bedit.strings.s65:115: .if acornsoft_version

Secret credits text change.

*** 58 .\pres_bedit.s65:84: .if acornsoft_version

Version number change

*** 59 .\pres_bedit.s65:89: .if bet2_version

ROM name change

*** 60 .\pres_bedit.s65:95: .if bet2_version

ROM version string change

*** 61 .\pres_bedit.s65:105: .if bet2_version

ROM copyright string change



** Bogus

Artefacts of the rather unclever search I did...

*** 53 .\pres_bedit.s65:24:acornsoft_version=false

Irrelevant

*** 54 .\pres_bedit.s65:25:bet2_version=false

Irrelevant

*** 55 .\pres_bedit.s65:43: .if bet2_version

Irrelevant - set contsants



*** 67 .\pres_bedit.s65:373: beq print_version_number

Irrelevant

*** 68 .\pres_bedit.s65:378:print_version_number:

Irrelevant

*** 69 .\pres_bedit.s65:380:print_version_number_loop:

Irrelevant

*** 70 .\pres_bedit.s65:385: bcc print_version_number_loop

Irrelevant

*** 71 .\pres_bedit.s65:611: .if bet2_version

Includestuff

*** 79 .\pres_bedit.s65:874: .if bet2_version

Includestuff

*** 80 .\pres_bedit.s65:1152: .if bet2_version

Includestuff

*** 81 .\pres_bedit.s65:1457: .if bet2_version

Includestuff


*** 87 .\pres_bedit.s65:1557: .if acornsoft_version

Includestuff

*** 88 .\pres_bedit.s65:1674: .if acornsoft_version

Includestuff

*** 89 .\pres_bedit.s65:1749: .if bet2_version

Includestuff

*** 90 .\pres_bedit.s65:1785: .if bet2_version

End of ROM bits for ABE

*** 91 .\pres_bedit.s65:1823: .if acornsoft_version

Includestuff

*** 92 .\pres_bedit.s65:1860: .if acornsoft_version

End of ROM filler for Acornsoft



** Done

Already included (one way or another) in the updated version.

*** Done: 20 .\pres_bedit.enter_edit_mode.s65:35: .if bet2_version

Don't do OSBYTE 219 on Electron.

*** 21 .\pres_bedit.enter_edit_mode.s65:42: .if bet2_version

More of #20.

*** Done: 43 .\pres_bedit.reset_keys_settings.s65:21: .if acornsoft_version

Reset soft key stuff.

*** Done: 44 .\pres_bedit.reset_keys_settings.s65:28: .if acornsoft_version

Reset soft key stuff.



** Uncategorized

*** 0 .\pres_bedit.BDD3.s65:131: .if bet2_version

find_mode_getch calls LBFB2.

acornsoft_version

edit mode command calls some other subroutine???

*** 6 .\pres_bedit.commands.toggle_insert_overtype.s65:82: .if acornsoft_version

uninline *FX138 call.

*** 7 .\pres_bedit.commands.toggle_insert_overtype.s65:95: .if bet2_version

extra case for run_or_exit: maybe do =*BUTILS=

*** 8 .\pres_bedit.commands.toggle_insert_overtype.s65:118: .if bet2_version

the uninlined *FX138 call called by #6 and #7

*** 13 .\pres_bedit.command_table.s65:103: .if bet2_version

Command table entries for new UTILS and UPDATE commands.

*** 16 .\pres_bedit.command_jump_table.s65:161: .if acornsoft_version

CMD_tab_key is now $ca

*** 17 .\pres_bedit.command_jump_table.s65:249: .if acornsoft_version

CMD_shift_tab_key is now $ba

*** 18 .\pres_bedit.command_jump_table.s65:255: .if bet2_version

New entries for UPDATE and UTILS

*** 19 .\pres_bedit.enter_edit_mode.s65:6: .if bet2_version

call_other_rom with $a on entry to edit mode.

*** 22 .\pres_bedit.edit_mode_loop.s65:14: .if acornsoft_version

Chaneg ZP address from 3A to 38

*** 23 .\pres_bedit.edit_mode_loop.s65:20: .if acornsoft_version

Some change to do with soft key expansions in progress??

*** 24 .\pres_bedit.edit_mode_loop.s65:55: .if bet2_version

???

*** 25 .\pres_bedit.edit_mode_loop.s65:66: .if acornsoft_version

Same as #16

*** 26 .\pres_bedit.edit_mode_loop.s65:86: .if acornsoft_version

Same as #22

*** 27 .\pres_bedit.edit_mode_loop.s65:131: .if acornsoft_version

Same as #16

*** 28 .\pres_bedit.edit_mode_loop.s65:162: .if bet2_version

Change shift+delete check for Electron - covered by Mince's changes?

*** 29 .\pres_bedit.edit_mode_loop.s65:170: .if bet2_version

More of #28 I think

*** 30 .\pres_bedit.edit_mode_loop.s65:177: .if bet2_version

Not sure. Related to #22??

*** 31 .\pres_bedit.edit_mode_loop.s65:189: .if acornsoft_version

Same as #16

*** 32 .\pres_bedit.edit_mode_loop.s65:195: .if bet2_version

See #30

*** 33 .\pres_bedit.edit_mode_loop.s65:202: .if acornsoft_version

Same as #16

*** 34 .\pres_bedit.edit_mode_loop.s65:244: .if bet2_version

Handle cursor differently on Electron.

*** 35 .\pres_bedit.edit_mode_loop.s65:252: .if bet2_version

See #34

*** 36 .\pres_bedit.edit_mode_loop.s65:277: .if bet2_version

See #34

*** 37 .\pres_bedit.edit_mode_loop.s65:283: .if bet2_version

See #34

*** 38 .\pres_bedit.edit_mode_loop.s65:291: .if bet2_version

See #34

*** 39 .\pres_bedit.edit_mode_loop.s65:329: .if bet2_version

See #34

*** 40 .\pres_bedit.edit_mode_loop.s65:335: .if acornsoft_version

See #34, but this is inside a =.if bet2_version= so I think I got
confused...

*** 41 .\pres_bedit.reset_keys_settings.s65:6: .if bet2_version

Don't do OSBYTE 219 on Electron

*** 42 .\pres_bedit.reset_keys_settings.s65:13: .if acornsoft_version

See #41.

Flush keyboard buffer on BBC.

*** 45 .\pres_bedit.strings.s65:7: .if acornsoft_version

Product name.

*** 46 .\pres_bedit.strings.s65:17: .if acornsoft_version

HUD change.

*** 47 .\pres_bedit.strings.s65:22: .if acornsoft_version

See #46.

*** 48 .\pres_bedit.strings.s65:27: .if acornsoft_version

See #46.

*** 49 .\pres_bedit.strings.s65:31: .if bet2_version

See #46.

*** 52 .\pres_bedit.strings.s65:121: .if bet2_version

Add *BUTILS text, new help subject, new =Load= and =Append= strings.

*** 56 .\pres_bedit.s65:52: .if acornsoft_version

See #55

*** 57 .\pres_bedit.s65:58: .if bet2_version

See #55

*** 62 .\pres_bedit.s65:125: .if bet2_version

stx $a8, sty $a9...???

*** 63 .\pres_bedit.s65:136: .if bet2_version

new check for custom OSWORD handling

*** 64 .\pres_bedit.s65:141: .if bet2_version

restore_a8_a9 as appropriate

*** 65 .\pres_bedit.s65:158: .if bet2_version

call_other_rom with A=3 when doing a * command

*** 66 .\pres_bedit.s65:325: .if acornsoft_version

Looks like a bug fix! Code does ldx #$11 (???) rather than lda #$11
(print char 17)

*** 72 .\pres_bedit.s65:744: .if bet2_version

Electron-related mode stuff??

*** 73 .\pres_bedit.s65:749: .if bet2_version

See #72

*** 74 .\pres_bedit.s65:795: .if acornsoft_version

???

*** 75 .\pres_bedit.s65:803: .if acornsoft_version

??? - see #74

*** 76 .\pres_bedit.s65:811: .if bet2_version

??? - see #74

*** 77 .\pres_bedit.s65:815: .if acornsoft_version

??? - see #74

*** 78 .\pres_bedit.s65:820: .if acornsoft_version

??? - see #74

*** 82 .\pres_bedit.s65:1487: .if bet2_version

Don't do OSBYTE 219 on Electron

*** 83 .\pres_bedit.s65:1494: .if bet2_version

See #82

*** 84 .\pres_bedit.s65:1500: .if acornsoft_version

Let F keys be F keys. But... won't this break stuff??

*** 85 .\pres_bedit.s65:1507: .if acornsoft_version

See #84, but for shift+F keys.

*** 86 .\pres_bedit.s65:1514: .if acornsoft_version

See #84, but for Ctrl+F keys.

* Release process

0. Make all changes necessary, update [[./release_README.md]] with an
   entry for the version, commit

1. =git push= so that GitHub has latest

2. =make release VER\=<<ver>>= - this will generate a zip file called
   =build/basic_editor-<<ver>>.zip=.

   The =release= target will fail if the working copy is dirty. Supply
   =DIRTY_OK\=1= to disable this

3. Visit https://github.com/tom-seddon/basic_editor/releases and click
   =Draft a new release=

4. Paste release name from =make release= output into the tag field,
   and use that as the release title too

5. Attach zip file to release (=make release= output includes the
   path)

6. Release description should be as follows:

   #+begin_src markdown
     Version history can be found here: https://github.com/tom-seddon/basic_editor/blob/b1c007288611fb8d28a479ba75db9192996f3347/docs/release_README.md
   #+end_src

7. Publish

* eof.
